### ISSUE TITLE
build of cq-server

### ISSUE THREAD

**Issue by jniclas** [szymansk/cadquery_arm64#1]
Hi,

thank you for bringing CadQuery to ARM Macs 👍🏻 

In the docker-compose-build.yml there is this part:

```
cq-server:
    image: szymanski2adesso/cq-server:amd64
    platform: linux/amd64
    build:
      context: ./cadquery-server
      dockerfile: Dockerfile      
    command: "run"
    ports:
      - "5050:5000"
```

but I can't see the ` ./cadquery-server` folder in the repository. How can I build the image?
